name: test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pip install django
          pip install dj_database_url
          pip install load_dotenv
          pip install django_bootstrap5
          pip install psycopg2-binary
          pip install django-filter
          pip install rollbar
          pip install whitenoise
          pip install pytest-django
          make tests
      - name: Test & publish code coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: qltcp_Qq8tyaQerUc3msyt
          files: reports/lcov.info
      